# Generated by Django 4.2.25 on 2025-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='currency',
            field=models.CharField(default='RUB', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='token',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
